### ISSUE TITLE
Contract verification is failed with @nomiconlabs/hardhat-etherscan

### ISSUE THREAD

**Issue by chokobole** [wemixkanvas/kanvas#15]
### Issue Type

Bug

### Kanvas Version

0.1.1

### OS Platform and Distribution

Linux Ubuntu 22.04

### Go version

go1.19.3 linux/amd64

### Node version

v16.14.2

### Current Behaviour?

contract verification with @nomiconlabas/hardhat-etherscan isn't working. I tried with a simple one, `ZKMerkleTrie.sol`. The package tried to find `@openzeppelin/contracts/utils/Address.sol:Address`, but it's not used anywhere in `ZKMerkleTrie.sol`. 

### Standalone code to reproduce the issue

You can test this on https://github.com/wemixkanvas/kanvas/tree/chore/add-contract-verification-function.
Below `0xDEfe9D4CAe49524Bd2cc1a12e273eE7327248b1b` is the address of `ZKMerkleTrie.sol` and `0x31DC81Df35562722CA26Df68D843Ce5fcf2Fa33e` is the address of `Poseidon2`.

```shell
> export PRIVATE_KEY_DEPLOYER_SEPOLIA=<>
> export ETHERCAN_API_KEY=<>
> npx hardhat verify --network sepolia 0xDEfe9D4CAe49524Bd2cc1a12e273eE7327248b1b 0x31DC81Df35562722CA26Df68D843Ce5fcf2Fa33e
```

### Relevant log output

```shell
[⠆] Compiling...
No files changed, compilation skipped
An unexpected error occurred:

TypeError: Cannot read properties of undefined (reading 'Address')
    at extractMatchingContractInformation (/Users/chokobole/Workspace/blockchain/lightscale/kanvas/node_modules/@nomiclabs/hardhat-etherscan/src/solc/bytecode.ts:162:58)
    at lookupMatchingBytecode (/Users/chokobole/Workspace/blockchain/lightscale/kanvas/node_modules/@nomiclabs/hardhat-etherscan/src/solc/bytecode.ts:142:39)
    at async inferContract (/Users/chokobole/Workspace/blockchain/lightscale/kanvas/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:570:27)
    at async SimpleTaskDefinition.action (/Users/chokobole/Workspace/blockchain/lightscale/kanvas/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:742:31)
    at async Environment._runTaskDefinition (/Users/chokobole/Workspace/blockchain/lightscale/kanvas/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/Users/chokobole/Workspace/blockchain/lightscale/kanvas/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async SimpleTaskDefinition.verifySubtask [as action] (/Users/chokobole/Workspace/blockchain/lightscale/kanvas/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:279:60)
    at async Environment._runTaskDefinition (/Users/chokobole/Workspace/blockchain/lightscale/kanvas/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/Users/chokobole/Workspace/blockchain/lightscale/kanvas/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async Environment._runTaskDefinition (/Users/chokobole/Workspace/blockchain/lightscale/kanvas/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
```

**Comment by Pangssu** [comment]
I have found the cause of the problem.

To use `hardhat-etherscan`, the build-info generated by Hardhat is required. However, in WEMIX Kanvas, Foundry generates the build-info instead of Hardhat, which causes the problem. It can be seen from the `foundry` property in the `hardhat.config.ts` file that build-info is generated by Foundry.

If you want to use the `etherscan verify` in the Foundry environment, you can do so using the following command: 
```shell
> forge verify-contract <Contract Address> <Contract Name> <Etherscan API Key> --chain <Network Name>.
```

**Comment by Pangssu** [comment]
Furthermore, if you want to verify all L1 contracts used in WEMIX Kanvas, 
run `npx hardhat forge-contract-verify --network <Network Name>`.

**Comment by chokobole** [comment]
I also have cross-checked all the Layer 1 contracts on https://sepolia.etherscan.io/, too! thanks
